import AppKit
import Foundation

@MainActor
enum Output {
    // Time for the target app to read the pasteboard after ⌘V before the
    // previous contents are put back.
    private static let restoreDelay: TimeInterval = 0.6

    // Marks the dictation as short-lived so clipboard managers skip it
    // (conventions from nspasteboard.org).
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    static func setClipboard(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // Pastes the text and restores the previous clipboard afterwards. The text
    // stays in the clipboard only when pasting is off or not possible.
    @discardableResult
    static func deliverAndPaste(_ text: String, paste: Bool) -> Bool {
        guard paste, Paste.isTrusted else {
            setClipboard(text)
            return false
        }

        let pasteboard = NSPasteboard.general
        let previous = copyItems(of: pasteboard)
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes { item.setData(Data(), forType: type) }
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        let ours = pasteboard.changeCount

        guard Paste.sendCommandV() else {
            setClipboard(text)
            return false
        }

        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
            // Leave the clipboard alone if anything was copied in the meantime.
            guard pasteboard.changeCount == ours else { return }
            pasteboard.clearContents()
            if !previous.isEmpty { pasteboard.writeObjects(previous) }
        }
        return true
    }

    private static func copyItems(of pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { original in
            let copy = NSPasteboardItem()
            for type in original.types {
                if let data = original.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }
}
